# Generated by Django 5.2.1 on 2025-05-28 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogBusca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('id_prod_hub', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('mensagem', models.TextField()),
                ('data_hora', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
